services:
  game-database:
    ports:
      - "5432:5432"    
    networks:
      - backend-net
      - frontend-net

  game-service:
    ports:
      - "4010:4010"
    networks:
      - backend-net
      - frontend-net


  